FROM python:3.12-slim as main
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt
RUN playwright install chromium --with-deps
CMD ["fastapi", "run", "main.py", "--port", "80", "--proxy-headers"]
